
typedef enum {
  xml_client_stat_ok = 0,
  xml_client_stat_err
} xml_client_error_t;

enum xml_client_result_type {
  xml_client_result_type_double = 0,
  xml_client_result_type_int,
  xml_client_result_type_string
};

typedef struct {
  uint64_t result_type;
  union {
    double result_d;
    int64_t result_i;
    char *result_s;
  } result;
} xml_client_result_t;


/*FLdigi XMLRPC methods*/

#define FLDIGI_XML_METHOD_CONF_DIR "fldigi.config_dir"
#define FLDIGI_XML_METHOD_CONF_DIR "fldigi.config_dir"
#define FLDIGI_XML_METHOD_LIST "fldigi.list"
#define FLDIGI_XML_METHOD_NAME "fldigi.name"
#define FLDIGI_XML_METHOD_NAME_VERSION "fldigi.name_version"
#define FLDIGI_XML_METHOD_TERMINATE "fldigi.terminate"
#define FLDIGI_XML_METHOD_VERSION "fldigi.version"
#define FLDIGI_XML_METHOD_VERSION_STRUCT "fldigi.version_struct"
#define FLDIGI_XML_METHOD_IO_ENABLE_ARQ "io.enable_arq"
#define FLDIGI_XML_METHOD_IO_ENABLE_KISS "io.enable_kiss"
#define FLDIGI_XML_METHOD_IO_IN_USE "io.in_use"
#define FLDIGI_XML_METHOD_LOG_CLEAR "log.clear"
#define FLDIGI_XML_METHOD_LOG_GET_AZ "log.get_az"
#define FLDIGI_XML_METHOD_LOG_GET_BAND "log.get_band"
#define FLDIGI_XML_METHOD_LOG_GET_CALL "log.get_call"
#define FLDIGI_XML_METHOD_LOG_GET_COUNTRY "log.get_country"
#define FLDIGI_XML_METHOD_LOG_GET_EXCHANGE "log.get_exchange"
#define FLDIGI_XML_METHOD_LOG_GET_FREQUENCY "log.get_frequency"
#define FLDIGI_XML_METHOD_LOG_GET_LOCATOR "log.get_locator"
#define FLDIGI_XML_METHOD_LOG_GET_NAME "log.get_name"
#define FLDIGI_XML_METHOD_LOG_GET_NOTES "log.get_notes"
#define FLDIGI_XML_METHOD_LOG_GET_PROVINCE "log.get_province"
#define FLDIGI_XML_METHOD_LOG_GET_QTH "log.get_qth"
#define FLDIGI_XML_METHOD_LOG_GET_RST_IN "log.get_rst_in"
#define FLDIGI_XML_METHOD_LOG_GET_RST_OUT "log.get_rst_out"
#define FLDIGI_XML_METHOD_LOG_GET_SERIAL_NUMBER "log.get_serial_number"
#define FLDIGI_XML_METHOD_LOG_GET_SERIAL_NUMBER_SENT "log.get_serial_number_sent"
#define FLDIGI_XML_METHOD_LOG_GET_STATE "log.get_state"
#define FLDIGI_XML_METHOD_LOG_GET_TIME_OFF "log.get_time_off"
#define FLDIGI_XML_METHOD_LOG_GET_TIME_ON "log.get_time_on"
#define FLDIGI_XML_METHOD_LOG_SET_CALL "log.set_call"
#define FLDIGI_XML_METHOD_LOG_SET_EXCHANGE "log.set_exchange"
#define FLDIGI_XML_METHOD_LOG_SET_LOCATOR "log.set_locator"
#define FLDIGI_XML_METHOD_LOG_SET_NAME "log.set_name"
#define FLDIGI_XML_METHOD_LOG_SET_QTH "log.set_qth"
#define FLDIGI_XML_METHOD_LOG_SET_RST_IN "log.set_rst_in"
#define FLDIGI_XML_METHOD_LOG_SET_RST_OUT "log.set_rst_out"
#define FLDIGI_XML_METHOD_LOG_SET_SERIAL_NUMBER "log.set_serial_number"
#define FLDIGI_XML_METHOD_MAIN_ABORT "main.abort"
#define FLDIGI_XML_METHOD_MAIN_GET_AFC "main.get_afc"
#define FLDIGI_XML_METHOD_MAIN_GET_CHAR_RATES "main.get_char_rates"
#define FLDIGI_XML_METHOD_MAIN_GET_CHAR_TIMING "main.get_char_timing"
#define FLDIGI_XML_METHOD_MAIN_GET_FREQUENCY "main.get_frequency"
#define FLDIGI_XML_METHOD_MAIN_GET_LOCK "main.get_lock"
#define FLDIGI_XML_METHOD_MAIN_GET_MAX_MACRO_ID "main.get_max_macro_id"
#define FLDIGI_XML_METHOD_MAIN_GET_REVERSE "main.get_reverse"
#define FLDIGI_XML_METHOD_MAIN_GET_RSID "main.get_rsid"
#define FLDIGI_XML_METHOD_MAIN_GET_TXID "main.get_txid"
#define FLDIGI_XML_METHOD_MAIN_GET_SQUELCH "main.get_squelch"
#define FLDIGI_XML_METHOD_MAIN_GET_SQUELCH_LEVEL "main.get_squelch_level"
#define FLDIGI_XML_METHOD_MAIN_GET_STATUS1 "main.get_status1"
#define FLDIGI_XML_METHOD_MAIN_GET_STATUS2 "main.get_status2"
#define FLDIGI_XML_METHOD_MAIN_GET_TRX_STATE "main.get_trx_state"
#define FLDIGI_XML_METHOD_MAIN_GET_TRX_STATUS "main.get_trx_status"
#define FLDIGI_XML_METHOD_MAIN_GET_TX_TIMING "main.get_tx_timing"
#define FLDIGI_XML_METHOD_MAIN_GET_WF_SIDEBAND "main.get_wf_sideband"
#define FLDIGI_XML_METHOD_MAIN_INC_FREQUENCY "main.inc_frequency"
#define FLDIGI_XML_METHOD_MAIN_INC_SQUELCH_LEVEL "main.inc_squelch_level"
#define FLDIGI_XML_METHOD_MAIN_RUN_MACRO "main.run_macro"
#define FLDIGI_XML_METHOD_MAIN_RX "main.rx"
#define FLDIGI_XML_METHOD_MAIN_RX_ONLY "main.rx_only"
#define FLDIGI_XML_METHOD_MAIN_RX_TX "main.rx_tx"
#define FLDIGI_XML_METHOD_MAIN_SET_AFC "main.set_afc"
#define FLDIGI_XML_METHOD_MAIN_SET_FREQUENCY "main.set_frequency"
#define FLDIGI_XML_METHOD_MAIN_SET_LOCK "main.set_lock"
#define FLDIGI_XML_METHOD_MAIN_SET_REVERSE "main.set_reverse"
#define FLDIGI_XML_METHOD_MAIN_SET_RSID "main.set_rsid"
#define FLDIGI_XML_METHOD_MAIN_SET_TXID "main.set_txid"
#define FLDIGI_XML_METHOD_MAIN_SET_SQUELCH "main.set_squelch"
#define FLDIGI_XML_METHOD_MAIN_SET_SQUELCH_LEVEL "main.set_squelch_level"
#define FLDIGI_XML_METHOD_MAIN_SET_WF_SIDEBAND "main.set_wf_sideband"
#define FLDIGI_XML_METHOD_MAIN_TOGGLE_AFC "main.toggle_afc"
#define FLDIGI_XML_METHOD_MAIN_TOGGLE_LOCK "main.toggle_lock"
#define FLDIGI_XML_METHOD_MAIN_TOGGLE_REVERSE "main.toggle_reverse"
#define FLDIGI_XML_METHOD_MAIN_TOGGLE_RSID "main.toggle_rsid"
#define FLDIGI_XML_METHOD_MAIN_TOGGLE_TXID "main.toggle_txid"
#define FLDIGI_XML_METHOD_MAIN_TOGGLE_SQUELCH "main.toggle_squelch"
#define FLDIGI_XML_METHOD_MAIN_TUNE "main.tune"
#define FLDIGI_XML_METHOD_MAIN_TX "main.tx"
#define FLDIGI_XML_METHOD_MODEM_GET_AFC_SEARCH_RANGE "modem.get_afc_search_range"
#define FLDIGI_XML_METHOD_MODEM_GET_BANDWIDTH "modem.get_bandwidth"
#define FLDIGI_XML_METHOD_MODEM_GET_CARRIER "modem.get_carrier"
#define FLDIGI_XML_METHOD_MODEM_GET_ID "modem.get_id"
#define FLDIGI_XML_METHOD_MODEM_GET_MAX_ID "modem.get_max_id"
#define FLDIGI_XML_METHOD_MODEM_GET_NAME "modem.get_name"
#define FLDIGI_XML_METHOD_MODEM_GET_NAMES "modem.get_names"
#define FLDIGI_XML_METHOD_MODEM_GET_QUALITY "modem.get_quality"
#define FLDIGI_XML_METHOD_MODEM_INC_AFC_SEARCH_RANGE "modem.inc_afc_search_range"
#define FLDIGI_XML_METHOD_MODEM_INC_BANDWIDTH "modem.inc_bandwidth"
#define FLDIGI_XML_METHOD_MODEM_INC_CARRIER "modem.inc_carrier"
#define FLDIGI_XML_METHOD_MODEM_OLIVIA_GET_BANDWIDTH "modem.olivia.get_bandwidth"
#define FLDIGI_XML_METHOD_MODEM_OLIVIA_GET_TONES "modem.olivia.get_tones"
#define FLDIGI_XML_METHOD_MODEM_OLIVIA_SET_BANDWIDTH "modem.olivia.set_bandwidth"
#define FLDIGI_XML_METHOD_MODEM_OLIVIA_SET_TONES "modem.olivia.set_tones"
#define FLDIGI_XML_METHOD_MODEM_SEARCH_DOWN "modem.search_down"
#define FLDIGI_XML_METHOD_MODEM_SEARCH_UP "modem.search_up"
#define FLDIGI_XML_METHOD_MODEM_SET_AFC_SEARCH_RANGE "modem.set_afc_search_range"
#define FLDIGI_XML_METHOD_MODEM_SET_BANDWIDTH "modem.set_bandwidth"
#define FLDIGI_XML_METHOD_MODEM_SET_BY_ID "modem.set_by_id"
#define FLDIGI_XML_METHOD_MODEM_SET_BY_NAME "modem.set_by_name"
#define FLDIGI_XML_METHOD_MODEM_SET_CARRIER "modem.set_carrier"
#define FLDIGI_XML_METHOD_NAVTEX_GET_MESSAGE "navtex.get_message"
#define FLDIGI_XML_METHOD_NAVTEX_SEND_MESSAGE "navtex.send_message"
#define FLDIGI_XML_METHOD_RIG_GET_BANDWIDTH "rig.get_bandwidth"
#define FLDIGI_XML_METHOD_RIG_GET_BANDWIDTHS "rig.get_bandwidths"
#define FLDIGI_XML_METHOD_RIG_GET_MODE "rig.get_mode"
#define FLDIGI_XML_METHOD_RIG_GET_MODES "rig.get_modes"
#define FLDIGI_XML_METHOD_RIG_GET_NAME "rig.get_name"
#define FLDIGI_XML_METHOD_RIG_GET_NOTCH "rig.get_notch"
#define FLDIGI_XML_METHOD_RIG_RELEASE_CONTROL "rig.release_control"
#define FLDIGI_XML_METHOD_RIG_SET_BANDWIDTH "rig.set_bandwidth"
#define FLDIGI_XML_METHOD_RIG_SET_BANDWIDTHS "rig.set_bandwidths"
#define FLDIGI_XML_METHOD_RIG_SET_FREQUENCY "rig.set_frequency"
#define FLDIGI_XML_METHOD_RIG_SET_MODE "rig.set_mode"
#define FLDIGI_XML_METHOD_RIG_SET_MODES "rig.set_modes"
#define FLDIGI_XML_METHOD_RIG_SET_NAME "rig.set_name"
#define FLDIGI_XML_METHOD_RIG_SET_PWRMETER "rig.set_pwrmeter"
#define FLDIGI_XML_METHOD_RIG_SET_SMETER "rig.set_smeter"
#define FLDIGI_XML_METHOD_RIG_TAKE_CONTROL "rig.take_control"
#define FLDIGI_XML_METHOD_RX_GET_DATA "rx.get_data"
#define FLDIGI_XML_METHOD_RXTX_GET_DATA "rxtx.get_data"
#define FLDIGI_XML_METHOD_SPOT_GET_AUTO "spot.get_auto"
#define FLDIGI_XML_METHOD_SPOT_PSKREP_GET_COUNT "spot.pskrep.get_count"
#define FLDIGI_XML_METHOD_SPOT_SET_AUTO "spot.set_auto"
#define FLDIGI_XML_METHOD_SPOT_TOGGLE_AUTO "spot.toggle_auto"
#define FLDIGI_XML_METHOD_TEXT_ADD_TX "text.add_tx"
#define FLDIGI_XML_METHOD_TEXT_ADD_TX_BYTES "text.add_tx_bytes"
#define FLDIGI_XML_METHOD_TEXT_CLEAR_RX "text.clear_rx"
#define FLDIGI_XML_METHOD_TEXT_CLEAR_TX "text.clear_tx"
#define FLDIGI_XML_METHOD_TEXT_GET_RX "text.get_rx"
#define FLDIGI_XML_METHOD_TEXT_GET_RX_LENGTH "text.get_rx_length"
#define FLDIGI_XML_METHOD_TX_GET_DATA "tx.get_data"
#define FLDIGI_XML_METHOD_WEFAX_END_RECEPTION "wefax.end_reception"
#define FLDIGI_XML_METHOD_WEFAX_GET_RECEIVED_FILE "wefax.get_received_file"
#define FLDIGI_XML_METHOD_WEFAX_SEND_FILE "wefax.send_file"
#define FLDIGI_XML_METHOD_WEFAX_SET_ADIF_LOG "wefax.set_adif_log"
#define FLDIGI_XML_METHOD_WEFAX_SET_MAX_LINES "wefax.set_max_lines"
#define FLDIGI_XML_METHOD_WEFAX_SET_TX_ABORT_FLAG "wefax.set_tx_abort_flag"
#define FLDIGI_XML_METHOD_WEFAX_SKIP_APT "wefax.skip_apt"
#define FLDIGI_XML_METHOD_WEFAX_SKIP_PHASING "wefax.skip_phasing"
#define FLDIGI_XML_METHOD_WEFAX_STATE_STRING "wefax.state_string"

int xml_cli_init(const char *host, u_int64_t port);
int xml_cli_get_call(const char *method_name, char *params, xml_client_result_t *result);
void xml_cli_close(void);
